### ISSUE TITLE
Feature proposal: autoupdate the rblist.info by importing the 550+ Yale list.

### ISSUE THREAD

**Issue by kaminski-pawel** [veelenga/rblist#12]
Feature proposal: autoupdate the rblist.info by importing the 550+ Yale list.

## Reason or Problem

Jeffrey Sonnenfeld from the Yale Chief Executive Leadership Institute continuously updates a [similar list](https://som.yale.edu/story/2022/over-400-companies-have-withdrawn-russia-some-remain). This list already has more than 500 companies, including companies that defy demands to exit the Russian market.

I don't know the source of rblist.info data, but the Sonnenfeld dataset seems very comprehensive.

## Proposal or Solution

I propose changing the way in which  rblist.info serves its data by importing the Sonnenfeld list. To my knowledge this data is exported only in the Excel format  (xlsx). The columns including 'name', 'logo' and 'action'. There is also a grading system (e.g grade B means suspension of activities in Russia).

To keep current rblist features, e.g. tags, those would have to be added to the dataset manually or in a half-automated fashion.

### Design

I see three main ways of getting there. 1) Make an separate public API. 2) Make a stand-alone script that exports the Excel file to JSON format compliance with current data structure. 3) Some .js or .ts feature that imports the data from .xlsx/.json in real time (?).

I can help with implementing option 1 and 2. Re. option 1 I can add API to my existing project (Django/Django Rest Framework), it can also be done as a separate project with AWS API Gateway and AWS Lambda. As for option 2 I can write a simple Python script. I guess I could also write it in JavaScript, but it would take longer for me to write.

I can provide more details if there is an interest in such feature :).

**Comment by veelenga** [comment]
@kaminski-pawel thank you for the interest. 

I am currently working on # 2 but using a different source: https://airtable.com/shri4fzaMzXrQ3ZHp/tbloSNFhgc3BjkuC8, which is also updated periodically. Can you suggest what source is better?

I am planning to deliver # 2 very soon, but in a long perspective, I would like to move to # 1 having AWS API Gateway and AWS Lambda. If you would like to provide some help with this, it would be perfect.

**Comment by kaminski-pawel** [comment]
The descriptions from the Yale list and the three first columns from Airtable list seem the same, so I guess those are from the same source, i.e. Jeffrey Sonnenfeld research group. The dataset from today can be found here:
https://som.yale.edu/story/2022/over-400-companies-have-withdrawn-russia-some-remain

The original however does not have the other columns.

I’ll try to write an OpenAPI specification for API Gateway +  Lambda function + IAM Policies + whatever is needed to run it. I’ll let you know not later than on Monday what I managed to do.
Will you host the AWS infrastructure? The expected AWS cost should be minimal.

Which dataset should I use? The original Yale one or the Airtable one, probably older but with more columns?

**Comment by veelenga** [comment]
> Will you host the AWS infrastructure?

Yes, I will host it.

> Which dataset should I use? The original Yale one or the Airtable one, probably older but with more columns?

Airtable has a Sector column, which I plan to use as a tag. So probably Airtable is a bit more useful?. 

Thanks a lot.

**Comment by kaminski-pawel** [comment]
Hello @veelenga,

I need more time with finishing the API. Hopefully on Tuesday or Wednesday an initial version will be ready.
You can check out the prototype API [here].
(https://r9nqtyg28c.execute-api.eu-north-1.amazonaws.com/test/companies)

I had some problems with an Airtable integration, so I ended up with joining the original Yale list with extended Airtable list. The Yale list is stored in Box, which has great API, so we can fetch the data directly from the Excel file. Airtable’s API seems lacking, but we can save the data manually to static JSON file and append the up-to-date data from Yale list with additional columns such as sector tags or links to images with logos. This way the list will be up to date and we’ll have the additional info.

The problem is that the Lambda function fetching data from Box takes too much time. So instead calling the Box API with every request I’m setting the Lambda function to periodically populate DynamoDB table, from where API Gateway takes data to serve incoming requests.

Please give your feedback on the prototype API. The columns from original Yale list are lowercase and from Airtable list are title case.

**Comment by veelenga** [comment]
@kaminski-pawel thank makes sense to me. I will make a branch with API integration meanwhile. Thanks for the help

**Comment by kaminski-pawel** [comment]
@veelenga, I’ve prepared API to automatically update on the basis on the original Yale list with additional columns from Airtable data. You can find the source code [here]( https://github.com/kaminski-pawel/yale-celi-list-of-companies). Changes are welcomed.

The Yale list’s structure was constantly changing, so I finally started fetching the data embedded in the html instead of the .xlsx file.

If needed, we could contact the Sonnenfeld’s team and help them to structure the data so that it can be utilized directly by the API. The project in its current form is too sensitive to any changes in the original data structure.

**Comment by veelenga** [comment]
@kaminski-pawel API looks amazing. 

The only improvement I would add is downloading the logos and putting them into S3 storage. My concern is that if AirTable removes the table it will break the links to all the logos on rblist.

I think I can do that on my own. Thanks a lot for the help

**Comment by kaminski-pawel** [comment]
@veelenga hope it helps. Let me know if you need anything :)

**Comment by veelenga** [comment]
@kaminski-pawel sorry, didn't have enough time to finish this. Still plan to integrate

**Comment by kaminski-pawel** [comment]
@veelenga, no problem. In the meantime Yale has added a new Airtable-based backend and a website to utilize it. 
https://www.yalerussianbusinessretreat.com/

This could open an opportunity to simplify the API even more. The Yale API has the following IDs: table `id=tbldUvNp7cLAmH8Lh` and `applicationId=app2U7ltMR2zyMWtq`, so using it could be as simple as:

```
import requests
headers = {'Authorization': f'Bearer {API_KEY}'} # Airtable account API key
response = requests.get('https://api.airtable.com/v0/app2U7ltMR2zyMWtq/tbldUvNp7cLAmH8Lh', headers=headers)
```

However, this will raise 403 ‘Invalid permissions’ error. I think with Airtable the database owner (Yale) has to grand at least read-only permission to the client’s account for this to work. I could be wrong about that, but it's defenitly worth reaching Yale team to ask for such access. You can write them at jeffrey.sonnenfeld.celi@yale.edu (Yale CELI president public mail).
